spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking
    username: root
    password: toor
    
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
      